Repository elbgoods/guidelines, pull requests merged in 2020-01, with the labels that each got.

#1 add json:api top level spec to own guidelines
  docs/api/README.md
Labels: api

#3 Create LICENSE
  LICENSE
Labels: general

#4 remove empty() from good examples
  docs/php/README.md
Labels: php

#5 implement prism nord theme
  docs/.vuepress/config.js
  docs/.vuepress/public/prism-nord-theme.css
Labels: general

#7 Update issue templates
  .github/ISSUE_TEMPLATE/to-be-defined-collection.md
Labels: general

#8 add algolia docsearch
  docs/.vuepress/config.js
Labels: general

#9 git docs
  docs/.vuepress/config.js
  docs/git/README.md
  docs/git/git-flow.svg
Labels: general

#10 remove duplicated empty headline
  docs/php/laravel/README.md
Labels: php
